version: '3.8'

services:
  ubuntu-ssh:
    build: .
    container_name: ubuntu_ssh_container
    ports:
      - "2222:22"
    volumes:
      - ./data:/data
    networks:
      - ubuntu_network

networks:
  ubuntu_network:
    driver: bridge

volumes:
  data:
